---
name: Infracost
on:
  pull_request:
    paths:
    - '**.tf'
    - '**.tfvars'
    - '**.tfvars.json'

jobs:
  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run infracost diff
      uses: infracost/infracost-gh-action@master
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Do not change
      with:
        entrypoint: /scripts/ci/diff.sh # Do not change
        path: terraform/examples/ec2-eu-west-2/
